[lint]
select = ["ALL"]
ignore = [
    "D100",
    "D103",
    "D104",
    "D203",
    "D213",
    "EM102",
    "PLC0415",
    "PLR0913",
    "T201",
    "TRY003",
]

[lint.per-file-ignores]
"utils/models.py" = [
    "B006",
    "D102",
    "D107",
]